vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        profile_picture:
            uri_prefix: /pictures/profile
            upload_destination: '%kernel.project_dir%/public/pictures/profile'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
