vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        profile_picture:
            uri_prefix: /media/profile
            upload_destination: '%kernel.project_dir%/public/media/profile'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_format: 'Y-d-m'
                    date_time_property: updatedAt
