name: Code linting

on: [pull_request]

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Start the containers
              run: make start-ci

            - name: Run PHP-CS-Fixer
              run: docker compose -f docker-compose.ci.yml exec php sh -c "PHP_CS_FIXER_IGNORE_ENV=1 ./vendor/bin/php-cs-fixer fix src -v --dry-run"

    eslint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Start the containers
              run: make start-ci

            - name: Run ESLint
              run: docker compose -f docker-compose.ci.yml exec php yarn lint
